### ISSUE TITLE
Certain viewBoxes show the wrong viewport

### ISSUE THREAD

**Issue by ygra** [fskpf/svg2roughjs#12]
Possibly due to negative coordinates?

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox='-50 -50 50 50' version="1.0">
<rect x='-48' y='-48' width='46' height='46' stroke='black' stroke-width='2' fill='none'/>
<circle cx='-25' cy='-25' r='20' fill='red'/>
</svg>
```

Expected:
![image](https://user-images.githubusercontent.com/1692688/73588841-53e9bb80-44ce-11ea-8603-3a84d75d1b62.png)

Actual:
![image](https://user-images.githubusercontent.com/1692688/73588844-5a783300-44ce-11ea-844c-1cf31e8f2150.png)

**Comment by fskpf** [comment]
I've pushed a fix for it (supposedly). Can you take a look at it? I'm not sure whether it actually fixes it or if it only works for this one. It seems to work with our current test images.

**Comment by ygra** [comment]
Looks good.
