### ISSUE TITLE
Polylines should honor fill

### ISSUE THREAD

**Issue by ygra** [fskpf/svg2roughjs#18]

**Comment by ygra** [comment]
This raises an interesting question about auto-stroking filled but unstroked shapes. This could happen here as well and may not like intended (since one line is missing). Perhaps doing the auto-stroke only on closed shapes (rect, circle, ellipse, polygon)? What about paths? Analyze every sub-path whether it's closed or not and perhaps split them based on that?

**Comment by fskpf** [comment]
I'd say doing it on only closed shapes works well for now. The paths could wait until it bugs us enough to do it properly.
