### ISSUE TITLE
Consider opacity attribute for fill and stroke

### ISSUE THREAD

**Issue by fskpf** [fskpf/svg2roughjs#19]
Consider opacity attribute for fill and stroke.

**Comment by fskpf** [comment]
What was this about? Cannot remember, and fill-opacity / stroke-opacity are parsed and applied.

**Comment by ygra** [comment]
This is about the shape's opacity, i.e. just `opacity`, which should apply to both `fill` and `stroke`, additionally to the `stroke-opacity` and `fill-opacity`.
