### ISSUE TITLE
Sample application ceases to work after the first error in code editor

### ISSUE THREAD

**Issue by ygra** [fskpf/svg2roughjs#32]
Page has to be reloaded in that case.

**Comment by fskpf** [comment]
How can I trigger this?

**Comment by ygra** [comment]
Happened for me basically every time when editing the SVG code.

**Comment by fskpf** [comment]
Somehow I'm still not able to trigger it (tried randomly deleting/adding text content in the editor).

Maybe it was a broken intermediate state or it needs some other editing gestures?!

**Comment by ygra** [comment]
Seems to only happen in Firefox, apparently. Chrome seems fine.

**Comment by fskpf** [comment]
A right, I've just pushed a changeset that re-sets the app state when this happens. Unfortunately on #43 ...
