### ISSUE TITLE
Transforms on use seem to get ignored at least partially

### ISSUE THREAD

**Issue by ygra** [fskpf/svg2roughjs#6]
E.g.:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox='0 0 324 216' width='900' height='600'>
<rect fill='#0F47AF' width='324' height='216'/>
<g stroke='#FCDD09' fill='none'>
<circle stroke-width='12' r='73' cx='162' cy='108'/>
<path id='p' stroke-width='8' d='M89,108h146M162,35v146'/>
<use xlink:href='#p' transform='translate(162,108) rotate(30) translate(-162,-108)'/>
<use xlink:href='#p' transform='translate(162,108) rotate(60) translate(-162,-108)'/>
</g>
<circle stroke-width='1' stroke='#BDBD00' fill='#FCDD09' r='16' cx='162' cy='108'/>
<circle fill='#0F47AF' r='7' cx='162' cy='108'/>
</svg>
```

**Comment by fskpf** [comment]
I think this is mainly due to a broken rotation, since this doesn't work either:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 324 216" width="900" height="600">
  <g stroke="#FCDD09" fill="none">
    <path id="p" stroke-width="8" d="M0,0h146" transform="rotate(60)"/>
  </g>
</svg>
```

**Comment by fskpf** [comment]
I think this is due to the point-wise transformation of the path-data. This
```
  if (command.type === SVGPathData.HORIZ_LINE_TO) {
      // x
      const { x } = this.applyMatrix(new Point(command.x, 0), svgTransform)
      transformed.x = x
  }
```
will just result in a long horizontal 'x' value. It cannot be rotated with this approach (same for vertical path commands).

**Comment by ygra** [comment]
Ah, perhaps we should rewrite `H` and `V` with `L` (and `T` with `Q` to avoid [this bug](https://github.com/pshihn/rough/pull/129) until it's fixed).

I've gone through the same with rounded rects, circles, and ellipses by now. Some path commands are unsuitable for how we currently handle transforms (mainly `H`, `V`, and `A`, since they cannot work with rotation and sometimes even scaling).

I'd still argue that a second mode where we simply adjust the transform of the canvas context when needed would also be necessary, but for now the current approach has the benefit that _everything_ is drawn in the visible coordinate system, so hatching looks consistent throughout.
