### ISSUE TITLE
[Question] From SVG file

### ISSUE THREAD

**Issue by pmatos** [fskpf/svg2roughjs#84]
Is there a way to pipe an svg file through svg2roughjs and obtain as an output a rough svg file?

**Comment by ygra** [comment]
This is its main purpose, yes. Do note, however, that this requires a browser and DOM environment to run, because it's otherwise a real pain to correctly handle SVG element attributes and CSS properly. So this isn't easily packageable as a normal executable right now.

**Comment by pmatos** [comment]
> This is its main purpose, yes. See the example project, for example, which does this. Do note, however, that this requires a browser and DOM environment to run, because it's otherwise a real pain to correctly handle SVG element attributes and CSS properly. So this isn't easily packageable as a normal executable right now.

ah, yes, that's where my question was heading towards. If this could be a normal executable. However as you say it does need a DOM environment. That's fine, i just needed some sort of confirmation about this. Thanks for the help. Closing.
