### ISSUE TITLE
Exception on certain paths

### ISSUE THREAD

**Issue by fskpf** [fskpf/svg2roughjs#9]
Exception when trying to convert
```
<svg xmlns="http://www.w3.org/2000/svg" 
  xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 300 300">
  <g stroke-width="38" stroke="#000">
    <g id="b" transform="translate(150 150)">
      <path id="a" fill="#ffb13b" d="M-84.1-15.9a22.4 22.4 0 100 31.8H84a22.4 22.4 0 100-31.8z"/>
      <use xlink:href="#a" transform="rotate(45)"/>
      <use xlink:href="#a" transform="rotate(90)"/>
      <use xlink:href="#a" transform="rotate(135)"/>
    </g>
  </g>
  <use xlink:href="#b"/>
</svg>
```
The exception:
```
Uncaught SyntaxError: Expected a flag, got "100" at index "27"
```
when trying to convert the path to absolute coordinates.

**Comment by ygra** [comment]
It's right, though, isn't it? the 100 would need to be either 1 or 0.

**Comment by ygra** [comment]
https://github.com/nfroidure/svg-pathdata/issues/36
https://github.com/nfroidure/svg-pathdata/pull/37

**Comment by ygra** [comment]
Exception is gone by now, but rendering is broken for that particular image ...

**Comment by fskpf** [comment]
The transform of the `#b` use is not applied correctly. Can be simplified to
```
<svg xmlns="http://www.w3.org/2000/svg" 
  xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 300 300" width="300" height="300">
  <g stroke-width="38" stroke="#000">
    <g id="b" transform="translate(150 150)">
      <path id="a" fill="#ffb13b" d="M-84.1-15.9a22.4 22.4 0 100 31.8H84a22.4 22.4 0 100-31.8z"/>
    </g>
  </g>
  <use xlink:href="#b"/>
</svg>
```

When adding `transform="translate(-150 -150)"` to the `#b` use (i.e. removing the transform), it looks like the image drawn from svg2roughjs except for the stroke, which seems to be applied to the use as well.

**Comment by fskpf** [comment]
Created a separate issue for the wrong stroke: #25
